[start]
cmd = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[build]
cmd = "cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"

[variables]
PYTHONPATH = "/app" 